import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { generateKeyPairSync, sign } from 'node:crypto';
const dir=mkdtempSync(join(tmpdir(),'balanceboard-test-'));
process.env.DB_PATH=join(dir,'test.sqlite');
process.env.APP_ORIGIN='http://localhost:5173';
process.env.GOOGLE_CLIENT_ID='test-client.apps.googleusercontent.com';
process.env.GOOGLE_CLIENT_SECRET='test-secret';
const {app}=await import('./server.js');
const server=app.listen(0);
const origin=`http://127.0.0.1:${server.address().port}`;
async function request(path,method='GET',body,session) {
  const response=await fetch(origin+path,{method,headers:{'Content-Type':'application/json',...(session?{Cookie:session}:{})},body:body?JSON.stringify(body):undefined});
  return {status:response.status,data:await response.json(),cookie:response.headers.get('set-cookie')?.split(';')[0]};
}
test('accounts, persistence, isolation, validation and logout',async()=>{
  try {
    const a=await request('/api/auth/register','POST',{username:'alice',password:'correct horse battery staple'});
    assert.equal(a.status,200);
    assert.equal((await request('/api/profile','GET',null,a.cookie)).data.alarm.enabled,true);
    const changed=await request('/api/profile','PATCH',{displayName:'Alice Example',email:'alice@school.example',alarm:{enabled:true,sound:true,vibrate:false,desktop:true,reminderMinutes:10}},a.cookie);
    assert.equal(changed.status,200);
    assert.equal(changed.data.displayName,'Alice Example');
    assert.equal((await request('/api/profile','GET',null,a.cookie)).data.alarm.vibrate,false);
    assert.equal((await request('/api/profile','PATCH',{displayName:'Bad',email:'invalid',alarm:{}},a.cookie)).status,400);
    const proxied=await fetch(origin+'/api/auth/register',{method:'POST',headers:{'Content-Type':'application/json',Origin:'http://localhost:5173'},body:JSON.stringify({username:'via_proxy',password:'correct horse battery staple'})});
    assert.equal(proxied.status,200);
    const hostile=await fetch(origin+'/api/auth/register',{method:'POST',headers:{'Content-Type':'application/json',Origin:'https://unrelated.example'},body:JSON.stringify({username:'hostile',password:'correct horse battery staple'})});
    assert.equal(hostile.status,403);
    const b=await request('/api/auth/register','POST',{username:'bob',password:'another excellent password'});
    assert.equal(b.status,200);
    assert.equal((await request('/api/dashboard')).status,401);
    const task=await request('/api/actions','POST',{type:'task.add',payload:{title:'Write report',focusMinutes:25}},a.cookie);
    assert.equal(task.status,200);
    const id=task.data.result.id;
    const session=await request('/api/actions','POST',{type:'session.add',payload:{type:'study',title:'Read',date:'2026-09-30',startTime:'10:00',duration:25}},a.cookie);
    assert.equal(session.status,200);
    assert.equal((await request('/api/dashboard','GET',null,a.cookie)).data.tasks.length,2);
    assert.equal((await request('/api/dashboard','GET',null,b.cookie)).data.tasks.length,0);
    assert.equal((await request('/api/profile','GET',null,b.cookie)).data.displayName,'');
    assert.equal((await request('/api/alarms/due?day=2026-09-30&time=10:00','GET',null,a.cookie)).data.alarms.length,1);
    assert.equal((await request('/api/alarms/due?day=2026-09-30&time=10:00','GET',null,b.cookie)).data.alarms.length,0);
    assert.equal((await request('/api/alarms/due?day=2026-09-30&time=25:00','GET',null,a.cookie)).status,400);
    assert.equal((await request('/api/profile','PATCH',{displayName:'Alice Example',email:'alice@school.example',alarm:{enabled:false,sound:true,vibrate:false,desktop:true,reminderMinutes:10}},a.cookie)).status,200);
    assert.equal((await request('/api/alarms/due?day=2026-09-30&time=10:00','GET',null,a.cookie)).data.alarms.length,0);
    assert.equal((await request('/api/actions','POST',{type:'session.add',payload:{type:'study',title:'Hijack',date:'2026-09-30',startTime:'11:00',duration:25,linkedItemId:id}},b.cookie)).status,404);
    assert.equal((await request('/api/actions','POST',{type:'wellness.mood',payload:{mood:'🙂',day:'2026-09-30'}},a.cookie)).status,200);
    assert.equal((await request('/api/dashboard?day=2026-09-30','GET',null,a.cookie)).data.wellness.mood,'🙂');
    assert.equal((await request('/api/dashboard?day=2026-10-01','GET',null,a.cookie)).data.wellness.mood,'');
    assert.equal((await request('/api/actions','POST',{type:'task.delete',payload:{id}},b.cookie)).status,404);
    assert.equal((await request('/api/actions','POST',{type:'task.time',payload:{id,minutes:-2}},a.cookie)).status,400);
    assert.equal((await request('/api/auth/login','POST',{username:'alice',password:'wrong password'})).status,401);
    const login=await request('/api/auth/login','POST',{username:'ALICE',password:'correct horse battery staple'});
    assert.equal(login.status,200);
    assert.equal((await request('/api/dashboard','GET',null,login.cookie)).data.scheduledSessions.length,1);
    assert.equal((await request('/api/profile','GET',null,login.cookie)).data.displayName,'Alice Example');
    assert.equal((await request('/api/profile/password','PATCH',{currentPassword:'wrong',newPassword:'a new very long password'},login.cookie)).status,401);
    assert.equal((await request('/api/profile/password','PATCH',{currentPassword:'correct horse battery staple',newPassword:'a new very long password'},login.cookie)).status,200);
    assert.equal((await request('/api/auth/login','POST',{username:'alice',password:'correct horse battery staple'})).status,401);
    assert.equal((await request('/api/auth/login','POST',{username:'alice',password:'a new very long password'})).status,200);
    const page=await fetch(origin+'/dashboard',{headers:{Accept:'text/html'}});
    assert.equal(page.status,200); assert.match(await page.text(),/BalanceBoard/);
    assert.equal((await request('/api/auth/logout','POST',{},login.cookie)).status,200);
    assert.equal((await request('/api/dashboard','GET',null,a.cookie)).status,401);
    assert.equal((await request('/api/auth/providers')).data.google,true);
    const start=await fetch(origin+'/api/auth/google',{redirect:'manual'});
    assert.equal(start.status,302);
    const authUrl=new URL(start.headers.get('location'));
    assert.equal(authUrl.origin,'https://accounts.google.com');
    assert.equal(authUrl.searchParams.get('redirect_uri'),'http://localhost:5173/api/auth/google/callback');
    assert.equal(authUrl.searchParams.get('code_challenge_method'),'S256');
    const flowCookie=start.headers.get('set-cookie').split(';')[0];
    const bad=await fetch(origin+'/api/auth/google/callback?state=wrong&code=abc',{headers:{Cookie:flowCookie},redirect:'manual'});
    assert.match(bad.headers.get('location'),/authError=google/);
    const {privateKey,publicKey}=generateKeyPairSync('rsa',{modulusLength:2048});
    const jwk=publicKey.export({format:'jwk'});
    const nonce=flowCookie.split('=')[1].split('.')[1];
    const claims={iss:'https://accounts.google.com',aud:process.env.GOOGLE_CLIENT_ID,sub:'unique-google-subject',email:'alice@example.com',email_verified:true,nonce,iat:Math.floor(Date.now()/1000),exp:Math.floor(Date.now()/1000)+3600};
    const encode=value=>Buffer.from(JSON.stringify(value)).toString('base64url');
    const body=`${encode({alg:'RS256',kid:'test-key'})}.${encode(claims)}`;
    const idToken=`${body}.${sign('RSA-SHA256',Buffer.from(body),privateKey).toString('base64url')}`;
    const originalFetch=globalThis.fetch;
    globalThis.fetch=(url,options)=>{
      if(String(url)==='https://oauth2.googleapis.com/token') return Promise.resolve(new Response(JSON.stringify({id_token:idToken}),{headers:{'Content-Type':'application/json'}}));
      if(String(url)==='https://www.googleapis.com/oauth2/v3/certs') return Promise.resolve(new Response(JSON.stringify({keys:[{...jwk,kid:'test-key',use:'sig'}]}),{headers:{'Content-Type':'application/json','Cache-Control':'max-age=300'}}));
      return originalFetch(url,options);
    };
    try {
      const callback=await fetch(origin+`/api/auth/google/callback?state=${authUrl.searchParams.get('state')}&code=fakecode`,{headers:{Cookie:flowCookie},redirect:'manual'});
      assert.equal(callback.status,303);
      assert.equal(callback.headers.get('location'),'http://localhost:5173/dashboard');
      const sessionCookie=callback.headers.get('set-cookie').match(/bb_session=[^;]+/)[0];
      assert.equal((await request('/api/dashboard','GET',null,sessionCookie)).data.tasks.length,0);
      assert.equal((await request('/api/profile','GET',null,sessionCookie)).data.provider,'Google');
      assert.equal((await request('/api/profile/password','PATCH',{currentPassword:'anything',newPassword:'a new very long password'},sessionCookie)).status,400);
      assert.equal((await request('/api/dashboard','GET',null,a.cookie)).status,401);
    } finally { globalThis.fetch=originalFetch; }
  } finally { server.close(); rmSync(dir,{recursive:true,force:true}); }
});
